// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_LogBox = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_Container1 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 320);
    lv_obj_set_height(ui_Container1, 240);
    lv_obj_set_x(ui_Container1, 34);
    lv_obj_set_y(ui_Container1, -22);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LogBox = lv_textarea_create(ui_Container1);
    lv_obj_set_width(ui_LogBox, lv_pct(100));
    lv_obj_set_height(ui_LogBox, lv_pct(100));
    lv_obj_set_align(ui_LogBox, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_LogBox, "Placeholder...");

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Container1 = NULL;
    ui_LogBox = NULL;

}
